# Generated by Django 4.2.3 on 2023-07-23 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="end",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Case end time"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="case",
            name="start",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Case start time"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="duplicate_allowed",
            field=models.BooleanField(
                default=False, help_text="Used to determine whether multiple of this item can be claimed per case"
            ),
        ),
    ]
