# Generated by Django 4.2.3 on 2023-07-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0003_case_end_case_start_item_duplicate_allowed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="end",
            field=models.TimeField(verbose_name="Case end time"),
        ),
        migrations.AlterField(
            model_name="case",
            name="start",
            field=models.TimeField(verbose_name="Case start time"),
        ),
    ]
