# Generated by Django 4.2.3 on 2023-07-23 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0004_alter_case_end_alter_case_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="cases", to="bills.profile"
            ),
        ),
    ]
