# Generated by Django 4.2.3 on 2023-08-02 01:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0006_alter_profile_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ItemGroup",
            new_name="EquivalentItem",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="item_group",
            new_name="equivalent_items",
        ),
        migrations.RemoveField(
            model_name="case",
            name="dob",
        ),
        migrations.RemoveField(
            model_name="case",
            name="initials",
        ),
        migrations.AddField(
            model_name="case",
            name="age",
            field=models.PositiveIntegerField(
                default=2,
                validators=[
                    django.core.validators.MinValueValidator(0, message="Age must be a positive number or zero."),
                    django.core.validators.MaxValueValidator(150, message="Age cannot exceed 150."),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="case",
            name="age_unit",
            field=models.CharField(choices=[("MO", "Months"), ("YE", "Years")], default="YE", max_length=2),
        ),
        migrations.AddField(
            model_name="item",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("BA", "Basic Unit"),
                    ("TI", "Time Unit"),
                    ("MO", "Modifying Unit"),
                    ("EX", "Therapeutic or Diagnostic Unit"),
                ],
                default="BA",
                max_length=2,
            ),
        ),
    ]
